name: Pogoda Alert

on:
  schedule:
    # Cron - sprawdzanie deszczu o 7:00, 10:00, 13:00, 19:00, 21:00
    - cron: '0 7,10,13,19,21 * * *'
  workflow_dispatch:  # pozwala uruchomić ręcznie

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
        run: python pogoda_alert.py --miasto "Szczecin" --prog-opad 50 --tg-token "$TG_TOKEN" --tg-chat "$TG_CHAT"
